// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBng6_Kqj8FVISYgHe952Uus4rx7wcfqnA',
    appId: '1:480188325405:web:ab9b1b806b6d68c1ba30f4',
    messagingSenderId: '480188325405',
    projectId: 'flutter-fan-ta93abe',
    authDomain: 'flutter-fan-ta93abe.firebaseapp.com',
    storageBucket: 'flutter-fan-ta93abe.appspot.com',
    measurementId: 'G-Z8FC440XJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2xHSXa1e2kBInQadi_yVu2_gT6epnGgM',
    appId: '1:480188325405:android:db8b5532371427b9ba30f4',
    messagingSenderId: '480188325405',
    projectId: 'flutter-fan-ta93abe',
    storageBucket: 'flutter-fan-ta93abe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwAA29eOTUV_T_xb9kV9yyZHRLfiCAlSw',
    appId: '1:480188325405:ios:1f22c430233f9c2fba30f4',
    messagingSenderId: '480188325405',
    projectId: 'flutter-fan-ta93abe',
    storageBucket: 'flutter-fan-ta93abe.appspot.com',
    iosClientId: '480188325405-jegdte9dg58vh34gd98cthev8gdcrq6r.apps.googleusercontent.com',
    iosBundleId: 'com.ta93abe.flutterFan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwAA29eOTUV_T_xb9kV9yyZHRLfiCAlSw',
    appId: '1:480188325405:ios:1f22c430233f9c2fba30f4',
    messagingSenderId: '480188325405',
    projectId: 'flutter-fan-ta93abe',
    storageBucket: 'flutter-fan-ta93abe.appspot.com',
    iosClientId: '480188325405-jegdte9dg58vh34gd98cthev8gdcrq6r.apps.googleusercontent.com',
    iosBundleId: 'com.ta93abe.flutterFan',
  );
}
